language: node_js
node_js:
- '8'
- '9'
- '10'
script: yarn test
after_success: yarn coverage
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: lifeomic/alpha-cli
    node: '8'
