name: Release

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.LIFEOMIC_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: Test
        run: |
          yarn install
          yarn test
      - name: Publish
        run: |
          yarn semantic-release
